dist: xenial
sudo: false
language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
  include:
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
      sudo: true

install:
  - pip install coveralls tox-travis
script:
  - tox
after_success:
  - coveralls
